#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/xresources

# merge in defaults and keymaps

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

# don't turn off the screen/monitor power
xset s off -dpms

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

eval $(gnome-keyring-daemon --start --components=secrets,ssh)
export SSH_AUTH_SOCK
udiskie --smart-tray &
exec i3
